package com.aaa.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andMakeIsNull() {
            addCriterion("make is null");
            return (Criteria) this;
        }

        public Criteria andMakeIsNotNull() {
            addCriterion("make is not null");
            return (Criteria) this;
        }

        public Criteria andMakeEqualTo(String value) {
            addCriterion("make =", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeNotEqualTo(String value) {
            addCriterion("make <>", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeGreaterThan(String value) {
            addCriterion("make >", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeGreaterThanOrEqualTo(String value) {
            addCriterion("make >=", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeLessThan(String value) {
            addCriterion("make <", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeLessThanOrEqualTo(String value) {
            addCriterion("make <=", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeLike(String value) {
            addCriterion("make like", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeNotLike(String value) {
            addCriterion("make not like", value, "make");
            return (Criteria) this;
        }

        public Criteria andMakeIn(List<String> values) {
            addCriterion("make in", values, "make");
            return (Criteria) this;
        }

        public Criteria andMakeNotIn(List<String> values) {
            addCriterion("make not in", values, "make");
            return (Criteria) this;
        }

        public Criteria andMakeBetween(String value1, String value2) {
            addCriterion("make between", value1, value2, "make");
            return (Criteria) this;
        }

        public Criteria andMakeNotBetween(String value1, String value2) {
            addCriterion("make not between", value1, value2, "make");
            return (Criteria) this;
        }

        public Criteria andLineIsNull() {
            addCriterion("line is null");
            return (Criteria) this;
        }

        public Criteria andLineIsNotNull() {
            addCriterion("line is not null");
            return (Criteria) this;
        }

        public Criteria andLineEqualTo(String value) {
            addCriterion("line =", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotEqualTo(String value) {
            addCriterion("line <>", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineGreaterThan(String value) {
            addCriterion("line >", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineGreaterThanOrEqualTo(String value) {
            addCriterion("line >=", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineLessThan(String value) {
            addCriterion("line <", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineLessThanOrEqualTo(String value) {
            addCriterion("line <=", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineLike(String value) {
            addCriterion("line like", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotLike(String value) {
            addCriterion("line not like", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineIn(List<String> values) {
            addCriterion("line in", values, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotIn(List<String> values) {
            addCriterion("line not in", values, "line");
            return (Criteria) this;
        }

        public Criteria andLineBetween(String value1, String value2) {
            addCriterion("line between", value1, value2, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotBetween(String value1, String value2) {
            addCriterion("line not between", value1, value2, "line");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBodyformIsNull() {
            addCriterion("bodyForm is null");
            return (Criteria) this;
        }

        public Criteria andBodyformIsNotNull() {
            addCriterion("bodyForm is not null");
            return (Criteria) this;
        }

        public Criteria andBodyformEqualTo(String value) {
            addCriterion("bodyForm =", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformNotEqualTo(String value) {
            addCriterion("bodyForm <>", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformGreaterThan(String value) {
            addCriterion("bodyForm >", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformGreaterThanOrEqualTo(String value) {
            addCriterion("bodyForm >=", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformLessThan(String value) {
            addCriterion("bodyForm <", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformLessThanOrEqualTo(String value) {
            addCriterion("bodyForm <=", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformLike(String value) {
            addCriterion("bodyForm like", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformNotLike(String value) {
            addCriterion("bodyForm not like", value, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformIn(List<String> values) {
            addCriterion("bodyForm in", values, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformNotIn(List<String> values) {
            addCriterion("bodyForm not in", values, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformBetween(String value1, String value2) {
            addCriterion("bodyForm between", value1, value2, "bodyform");
            return (Criteria) this;
        }

        public Criteria andBodyformNotBetween(String value1, String value2) {
            addCriterion("bodyForm not between", value1, value2, "bodyform");
            return (Criteria) this;
        }

        public Criteria andEngineIsNull() {
            addCriterion("engine is null");
            return (Criteria) this;
        }

        public Criteria andEngineIsNotNull() {
            addCriterion("engine is not null");
            return (Criteria) this;
        }

        public Criteria andEngineEqualTo(String value) {
            addCriterion("engine =", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotEqualTo(String value) {
            addCriterion("engine <>", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineGreaterThan(String value) {
            addCriterion("engine >", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineGreaterThanOrEqualTo(String value) {
            addCriterion("engine >=", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineLessThan(String value) {
            addCriterion("engine <", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineLessThanOrEqualTo(String value) {
            addCriterion("engine <=", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineLike(String value) {
            addCriterion("engine like", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotLike(String value) {
            addCriterion("engine not like", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineIn(List<String> values) {
            addCriterion("engine in", values, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotIn(List<String> values) {
            addCriterion("engine not in", values, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineBetween(String value1, String value2) {
            addCriterion("engine between", value1, value2, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotBetween(String value1, String value2) {
            addCriterion("engine not between", value1, value2, "engine");
            return (Criteria) this;
        }

        public Criteria andTransmissionIsNull() {
            addCriterion("transmission is null");
            return (Criteria) this;
        }

        public Criteria andTransmissionIsNotNull() {
            addCriterion("transmission is not null");
            return (Criteria) this;
        }

        public Criteria andTransmissionEqualTo(String value) {
            addCriterion("transmission =", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotEqualTo(String value) {
            addCriterion("transmission <>", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionGreaterThan(String value) {
            addCriterion("transmission >", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionGreaterThanOrEqualTo(String value) {
            addCriterion("transmission >=", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionLessThan(String value) {
            addCriterion("transmission <", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionLessThanOrEqualTo(String value) {
            addCriterion("transmission <=", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionLike(String value) {
            addCriterion("transmission like", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotLike(String value) {
            addCriterion("transmission not like", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionIn(List<String> values) {
            addCriterion("transmission in", values, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotIn(List<String> values) {
            addCriterion("transmission not in", values, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionBetween(String value1, String value2) {
            addCriterion("transmission between", value1, value2, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotBetween(String value1, String value2) {
            addCriterion("transmission not between", value1, value2, "transmission");
            return (Criteria) this;
        }

        public Criteria andBodycolorIsNull() {
            addCriterion("bodyColor is null");
            return (Criteria) this;
        }

        public Criteria andBodycolorIsNotNull() {
            addCriterion("bodyColor is not null");
            return (Criteria) this;
        }

        public Criteria andBodycolorEqualTo(String value) {
            addCriterion("bodyColor =", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorNotEqualTo(String value) {
            addCriterion("bodyColor <>", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorGreaterThan(String value) {
            addCriterion("bodyColor >", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorGreaterThanOrEqualTo(String value) {
            addCriterion("bodyColor >=", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorLessThan(String value) {
            addCriterion("bodyColor <", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorLessThanOrEqualTo(String value) {
            addCriterion("bodyColor <=", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorLike(String value) {
            addCriterion("bodyColor like", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorNotLike(String value) {
            addCriterion("bodyColor not like", value, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorIn(List<String> values) {
            addCriterion("bodyColor in", values, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorNotIn(List<String> values) {
            addCriterion("bodyColor not in", values, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorBetween(String value1, String value2) {
            addCriterion("bodyColor between", value1, value2, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andBodycolorNotBetween(String value1, String value2) {
            addCriterion("bodyColor not between", value1, value2, "bodycolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorIsNull() {
            addCriterion("InteriorColor is null");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorIsNotNull() {
            addCriterion("InteriorColor is not null");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorEqualTo(String value) {
            addCriterion("InteriorColor =", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorNotEqualTo(String value) {
            addCriterion("InteriorColor <>", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorGreaterThan(String value) {
            addCriterion("InteriorColor >", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorGreaterThanOrEqualTo(String value) {
            addCriterion("InteriorColor >=", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorLessThan(String value) {
            addCriterion("InteriorColor <", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorLessThanOrEqualTo(String value) {
            addCriterion("InteriorColor <=", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorLike(String value) {
            addCriterion("InteriorColor like", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorNotLike(String value) {
            addCriterion("InteriorColor not like", value, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorIn(List<String> values) {
            addCriterion("InteriorColor in", values, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorNotIn(List<String> values) {
            addCriterion("InteriorColor not in", values, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorBetween(String value1, String value2) {
            addCriterion("InteriorColor between", value1, value2, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andInteriorcolorNotBetween(String value1, String value2) {
            addCriterion("InteriorColor not between", value1, value2, "interiorcolor");
            return (Criteria) this;
        }

        public Criteria andCostIsNull() {
            addCriterion("cost is null");
            return (Criteria) this;
        }

        public Criteria andCostIsNotNull() {
            addCriterion("cost is not null");
            return (Criteria) this;
        }

        public Criteria andCostEqualTo(BigDecimal value) {
            addCriterion("cost =", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotEqualTo(BigDecimal value) {
            addCriterion("cost <>", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostGreaterThan(BigDecimal value) {
            addCriterion("cost >", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cost >=", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostLessThan(BigDecimal value) {
            addCriterion("cost <", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cost <=", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostIn(List<BigDecimal> values) {
            addCriterion("cost in", values, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotIn(List<BigDecimal> values) {
            addCriterion("cost not in", values, "cost");
            return (Criteria) this;
        }

        public Criteria andCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost between", value1, value2, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost not between", value1, value2, "cost");
            return (Criteria) this;
        }

        public Criteria andSellingpriceIsNull() {
            addCriterion("sellingPrice is null");
            return (Criteria) this;
        }

        public Criteria andSellingpriceIsNotNull() {
            addCriterion("sellingPrice is not null");
            return (Criteria) this;
        }

        public Criteria andSellingpriceEqualTo(BigDecimal value) {
            addCriterion("sellingPrice =", value, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceNotEqualTo(BigDecimal value) {
            addCriterion("sellingPrice <>", value, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceGreaterThan(BigDecimal value) {
            addCriterion("sellingPrice >", value, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sellingPrice >=", value, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceLessThan(BigDecimal value) {
            addCriterion("sellingPrice <", value, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sellingPrice <=", value, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceIn(List<BigDecimal> values) {
            addCriterion("sellingPrice in", values, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceNotIn(List<BigDecimal> values) {
            addCriterion("sellingPrice not in", values, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellingPrice between", value1, value2, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andSellingpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellingPrice not between", value1, value2, "sellingprice");
            return (Criteria) this;
        }

        public Criteria andPimageIsNull() {
            addCriterion("pImage is null");
            return (Criteria) this;
        }

        public Criteria andPimageIsNotNull() {
            addCriterion("pImage is not null");
            return (Criteria) this;
        }

        public Criteria andPimageEqualTo(String value) {
            addCriterion("pImage =", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageNotEqualTo(String value) {
            addCriterion("pImage <>", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageGreaterThan(String value) {
            addCriterion("pImage >", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageGreaterThanOrEqualTo(String value) {
            addCriterion("pImage >=", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageLessThan(String value) {
            addCriterion("pImage <", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageLessThanOrEqualTo(String value) {
            addCriterion("pImage <=", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageLike(String value) {
            addCriterion("pImage like", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageNotLike(String value) {
            addCriterion("pImage not like", value, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageIn(List<String> values) {
            addCriterion("pImage in", values, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageNotIn(List<String> values) {
            addCriterion("pImage not in", values, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageBetween(String value1, String value2) {
            addCriterion("pImage between", value1, value2, "pimage");
            return (Criteria) this;
        }

        public Criteria andPimageNotBetween(String value1, String value2) {
            addCriterion("pImage not between", value1, value2, "pimage");
            return (Criteria) this;
        }

        public Criteria andPstatusIsNull() {
            addCriterion("pStatus is null");
            return (Criteria) this;
        }

        public Criteria andPstatusIsNotNull() {
            addCriterion("pStatus is not null");
            return (Criteria) this;
        }

        public Criteria andPstatusEqualTo(String value) {
            addCriterion("pStatus =", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusNotEqualTo(String value) {
            addCriterion("pStatus <>", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusGreaterThan(String value) {
            addCriterion("pStatus >", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusGreaterThanOrEqualTo(String value) {
            addCriterion("pStatus >=", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusLessThan(String value) {
            addCriterion("pStatus <", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusLessThanOrEqualTo(String value) {
            addCriterion("pStatus <=", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusLike(String value) {
            addCriterion("pStatus like", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusNotLike(String value) {
            addCriterion("pStatus not like", value, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusIn(List<String> values) {
            addCriterion("pStatus in", values, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusNotIn(List<String> values) {
            addCriterion("pStatus not in", values, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusBetween(String value1, String value2) {
            addCriterion("pStatus between", value1, value2, "pstatus");
            return (Criteria) this;
        }

        public Criteria andPstatusNotBetween(String value1, String value2) {
            addCriterion("pStatus not between", value1, value2, "pstatus");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andPcommentIsNull() {
            addCriterion("pComment is null");
            return (Criteria) this;
        }

        public Criteria andPcommentIsNotNull() {
            addCriterion("pComment is not null");
            return (Criteria) this;
        }

        public Criteria andPcommentEqualTo(String value) {
            addCriterion("pComment =", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentNotEqualTo(String value) {
            addCriterion("pComment <>", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentGreaterThan(String value) {
            addCriterion("pComment >", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentGreaterThanOrEqualTo(String value) {
            addCriterion("pComment >=", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentLessThan(String value) {
            addCriterion("pComment <", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentLessThanOrEqualTo(String value) {
            addCriterion("pComment <=", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentLike(String value) {
            addCriterion("pComment like", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentNotLike(String value) {
            addCriterion("pComment not like", value, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentIn(List<String> values) {
            addCriterion("pComment in", values, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentNotIn(List<String> values) {
            addCriterion("pComment not in", values, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentBetween(String value1, String value2) {
            addCriterion("pComment between", value1, value2, "pcomment");
            return (Criteria) this;
        }

        public Criteria andPcommentNotBetween(String value1, String value2) {
            addCriterion("pComment not between", value1, value2, "pcomment");
            return (Criteria) this;
        }

        public Criteria andCreatepersonIsNull() {
            addCriterion("createPerson is null");
            return (Criteria) this;
        }

        public Criteria andCreatepersonIsNotNull() {
            addCriterion("createPerson is not null");
            return (Criteria) this;
        }

        public Criteria andCreatepersonEqualTo(String value) {
            addCriterion("createPerson =", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotEqualTo(String value) {
            addCriterion("createPerson <>", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonGreaterThan(String value) {
            addCriterion("createPerson >", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonGreaterThanOrEqualTo(String value) {
            addCriterion("createPerson >=", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonLessThan(String value) {
            addCriterion("createPerson <", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonLessThanOrEqualTo(String value) {
            addCriterion("createPerson <=", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonLike(String value) {
            addCriterion("createPerson like", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotLike(String value) {
            addCriterion("createPerson not like", value, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonIn(List<String> values) {
            addCriterion("createPerson in", values, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotIn(List<String> values) {
            addCriterion("createPerson not in", values, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonBetween(String value1, String value2) {
            addCriterion("createPerson between", value1, value2, "createperson");
            return (Criteria) this;
        }

        public Criteria andCreatepersonNotBetween(String value1, String value2) {
            addCriterion("createPerson not between", value1, value2, "createperson");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 18 14:38:19 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}