package com.aaa.entity;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class Product {
    @DateTimeFormat
    private Date beginTime;
    @DateTimeFormat
    private Date endTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.make
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String make;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.line
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.bodyForm
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String bodyform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.engine
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String engine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.transmission
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String transmission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.bodyColor
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String bodycolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.InteriorColor
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String interiorcolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cost
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sellingPrice
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private BigDecimal sellingprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pImage
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String pimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pStatus
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String pstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createTime
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pComment
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String pcomment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createPerson
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    private String createperson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.make
     *
     * @return the value of product.make
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getMake() {
        return make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.make
     *
     * @param make the value for product.make
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setMake(String make) {
        this.make = make == null ? null : make.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.line
     *
     * @return the value of product.line
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.line
     *
     * @param line the value for product.line
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.bodyForm
     *
     * @return the value of product.bodyForm
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getBodyform() {
        return bodyform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.bodyForm
     *
     * @param bodyform the value for product.bodyForm
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setBodyform(String bodyform) {
        this.bodyform = bodyform == null ? null : bodyform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.engine
     *
     * @return the value of product.engine
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.engine
     *
     * @param engine the value for product.engine
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.transmission
     *
     * @return the value of product.transmission
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getTransmission() {
        return transmission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.transmission
     *
     * @param transmission the value for product.transmission
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setTransmission(String transmission) {
        this.transmission = transmission == null ? null : transmission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.bodyColor
     *
     * @return the value of product.bodyColor
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getBodycolor() {
        return bodycolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.bodyColor
     *
     * @param bodycolor the value for product.bodyColor
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setBodycolor(String bodycolor) {
        this.bodycolor = bodycolor == null ? null : bodycolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.InteriorColor
     *
     * @return the value of product.InteriorColor
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getInteriorcolor() {
        return interiorcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.InteriorColor
     *
     * @param interiorcolor the value for product.InteriorColor
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setInteriorcolor(String interiorcolor) {
        this.interiorcolor = interiorcolor == null ? null : interiorcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cost
     *
     * @return the value of product.cost
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cost
     *
     * @param cost the value for product.cost
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sellingPrice
     *
     * @return the value of product.sellingPrice
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public BigDecimal getSellingprice() {
        return sellingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sellingPrice
     *
     * @param sellingprice the value for product.sellingPrice
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setSellingprice(BigDecimal sellingprice) {
        this.sellingprice = sellingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pImage
     *
     * @return the value of product.pImage
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getPimage() {
        return pimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pImage
     *
     * @param pimage the value for product.pImage
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setPimage(String pimage) {
        this.pimage = pimage == null ? null : pimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pStatus
     *
     * @return the value of product.pStatus
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getPstatus() {
        return pstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pStatus
     *
     * @param pstatus the value for product.pStatus
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setPstatus(String pstatus) {
        this.pstatus = pstatus == null ? null : pstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createTime
     *
     * @return the value of product.createTime
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createTime
     *
     * @param createtime the value for product.createTime
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pComment
     *
     * @return the value of product.pComment
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getPcomment() {
        return pcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pComment
     *
     * @param pcomment the value for product.pComment
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setPcomment(String pcomment) {
        this.pcomment = pcomment == null ? null : pcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createPerson
     *
     * @return the value of product.createPerson
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public String getCreateperson() {
        return createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createPerson
     *
     * @param createperson the value for product.createPerson
     *
     * @mbg.generated Tue Dec 18 14:34:42 CST 2018
     */
    public void setCreateperson(String createperson) {
        this.createperson = createperson == null ? null : createperson.trim();
    }
}